site_name: USU Mars Rover Team Documentation
site_url: https://usumarsroverteam.github.io

theme:
  name: material
  favicon: assets/marsroverwhiteicon.png
  logo: assets/marsroverwhite.png
  font:
    text: Atkinson Hyperlegible
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.collapse
    - navigation.indexes
    - navigation.top
extra_css:
  - stylesheets/extra.css

nav:
  - Home:
      - index.md
      - Suggested Schedule: home/suggested-schedule.md
      - Future Work: home/future-work.md
  - System Overview:
      - sys-overview/index.md
      - Comms and Controls: sys-overview/comms-ctrls.md
      - Chassis/Frame: sys-overview/chassis.md
      - Drive System: sys-overview/drive.md
      - Robotic Arm: sys-overview/arm.md
      - Science Module: sys-overview/sci.md
      - Autonomous Software: sys-overview/autonomous-software.md
      - Autonomous Hardware: sys-overview/autonomous-hardware.md
      - Drone: sys-overview/drone.md
  - Appendix:
      - appendix/index.md
      - Datasheets: appendix/datasheets.md
      - Wiring Diagrams: appendix/wiring-diagrams.md
      - How-Tos: appendix/how-tos.md

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocs-pdf

extra_javascript:
  - javascripts/mermaid.mjs
